apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mariadb
        image: mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: mariadb
        - name: MARIADB_DATABASE
          value: mariadb
        - name: MARIADB_USER
          value: mariadb
        - name: MARIADB_PASSWORD
          value: mariadb
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: LoadBalancer